version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
  db_admin:
    container_name: pgadmin_container
    restart: always
    image: dpage/pgadmin4
    ports:
      - '80:80'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}'
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
    depends_on:
      - db
    links:
      - 'db:database'
